# .github/workflows/call-build.yml in caller-action-repo
name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: sai6993/my-node-app/.github/workflows/build-and-push.yml@<commit-SHA>
    with:
      tag: "latest"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
